import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import dynamic from "next/dynamic";
import { ThemeProvider } from "next-themes";
import MuiThemeProviderWrapper from "@/components/MuiThemeProviderWrapper";
import AppWrapper from "@/components/AppWrapper";

const inter = Inter({ subsets: ["latin"] });
const AuthGuard = dynamic(() => import("@/components/AuthGuard"), {
  ssr: false,
});

export const metadata: Metadata = {
  title: "Manager Web App",
  description: "Generated by Kang",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" enableSystem={false}>
          <MuiThemeProviderWrapper>
            <AppWrapper> {/* bọc ở đây */}
              <AuthGuard>{children}</AuthGuard>
            </AppWrapper>
          </MuiThemeProviderWrapper>

          {/* ToastContainer cho react-toastify */}
          <ToastContainer
            position="top-right"
            autoClose={3000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
          />        </ThemeProvider>
      </body>
    </html>
  );
}
